"""empty message

Revision ID: 07edd28d8a91
Revises: 821cf7687ae4
Create Date: 2024-01-24 15:46:51.298252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07edd28d8a91'
down_revision = '821cf7687ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=12), nullable=True))
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('length',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
